### ISSUE TITLE
Geeq cases changed in development version of the API

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/gemma.R#36]
Currently https://dev.gemma.msl.ubc.ca/rest/v2/datasets/1 returns geeq ids with different cases than https://gemma.msl.ubc.ca/rest/v2/datasets/1. Talking to @arteymix about them

**Comment by arteymix** [comment]
Fixed in https://github.com/PavlidisLab/Gemma/commit/e59a545030c056a125554dfa31eae1a1415f7f72
