### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by yavyx** [PavlidisLab/gemma.R#8]
Small issues in documentation :

- [ ] Filter parameter in `getDatasetData`
- [ ] Wrong description in OG API documentation for `getGeneLocationOnTaxon`

**Comment by jsicherman** [comment]
A few of them might also be wrong due to different defaults. I think some of them have, for example, `limit=20` with other ones having `limit=0`. Ideally, Guillaume will implement OpenAPI and make our job easier but otherwise there's a few small issues with docu strings.
